---
- hosts: all
  user: vagrant
  become: yes
  
  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=86400
  
    - name: Install required packages
      apt:
        name: 
          - nginx
          - python3
          - python3-pip
#           - python-pip

    - name: Install python-crontab lib
      pip:
          name: python-crontab
          executable: pip3

    - name: Create tmp dirs
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /tmp/files
        - /tmp/scripts
 
#     - name: Copy cron runnig script
#       copy:
#           src: file_cron.py
#           dest: /tmp/scripts/file_cron.py
#           mode: "0777"

    - name: Start nginx service
      service:
          name: nginx
          state: started

    - name: Copy nginx.conf
      template:
          src: nginx.conf
          dest: /etc/nginx/nginx.conf
      notify: restart nginx

    - name: Copy service_state file
      copy:
          src=service_state
          dest=/tmp/files/service_state
      notify:
          - replace state file
          - restart nginx
          - run cron

  handlers:
    - name: restart nginx
      service:
          name: nginx
          state: restarted

    - name: run cron 
      command: python3 /tmp/scripts/file_cron.py

    - name: replace state file
      command: cp /tmp/files/service_state /opt/service_state
