---
- hosts: all
  user: vagrant
  become: yes
  
  tasks:
    - name: update_cache
      apt: update_cache=yes cache_valid_time=86400
  
    - name: packages_installing
      apt:
        name: 
          - nginx
          - python3
          - python3-pip
#           - python-pip

    - name: install_crontab_lib
      pip3: name=python-crontab executable=pip3

    - name: create_dir_for_files
      file:
        path: /tmp/ansible_hw
        state: directory

    - name: Start nginx service
      service:
          name: nginx
          state: started

    - name: Copy nginx.conf
      template:
          src: nginx.conf
          dest: /etc/nginx/nginx.conf
      notify: restart nginx

    - name: Copy service_state file
      copy:
          src=service_state
          dest=/tmp/ansible_hw/service_state
      notify:
          - replace state file
          - restart nginx
          - run cron

  handlers:
    - name: restart nginx
      service:
          name: nginx
          state: restarted

    - name: run cron 
      command: python3 /tmp/ansible_hw/file_cron.py

    - name: replace state file
      command: cp /tmp/ansible_hw/service_state /opt/service_state
