---
- hosts: all
  user: vagrant
  become: yes
  
  tasks:
#     - name: update_cache
#       apt: update_cache=yes cache_valid_time=86400
  
    - name: packages_installing
      apt:
        name:
          - python3
          - python-pip
          - python3-pip
          - nginx

    - name: install_crontab_lib
      pip: name=python-crontab executable=pip3

    - name: create_dir_for_files
      file:
        path: /tmp/ansible_hw
        state: directory

    - name: nginx_start
      service:
          name: nginx
          state: started

    - name: check_conf_for_nginx
      template:
          src: nginx.conf
          dest: /etc/nginx/nginx.conf
      notify: restart_nginx

    - name: python_cron_copy
      template:
          src: file_cron.py
          dest: /tmp/ansible_hw/file_cron.py
      notify: python_cron_start

    - name: service_state_copy
      copy:
          src=service_state
          dest=/tmp/ansible_hw/service_state
      notify:
          - put_service_state
          - restart_nginx
          - python_cron_start

  handlers:
    - name: restart_nginx
      service:
          name: nginx
          state: restarted
    
    - name: put_service_state
      command: cp /tmp/ansible_hw/service_state /opt/service_state
      
    - name: python_cron_start 
      command: python3 /tmp/ansible_hw/file_cron.py
