version: "3.0"

services:
  database:
    image: "mysql:8.0.26"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: products_db
      MYSQL_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: on-failure

  service-2:
    build:
      context: .
      dockerfile: service-2/Dockerfile
    restart: on-failure
    depends_on:
      - database

  service-3:
    build:
      context: .
      dockerfile: service-3/Dockerfile
    restart: on-failure
    depends_on:
      - database
    environment:
      FLASK_APP: service-3
    ports:
      - 10995:5000
