version: "3.0"

services:
  database:
    image: "mysql:8.0.1"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: on-failure

  service-2:
    build:
      context: .
      dockerfile: service-2/Dockerfile-2
    volumes:
      - dbdata:/dbdata
    restart: on-failure
    depends_on:
      - database

  service-3:
    build:
      context: .
      dockerfile: service-3/Dockerfile-3
    restart: on-failure
    depends_on:
      - database
    environment:
      FLASK_APP: service-3
    ports:
      - 17500:5000

volumes:
  dbdata:
